### ISSUE TITLE
IPFS support

### ISSUE THREAD

**Issue by TimosCatell** [DoseLibrary/ContentServer#10]
Any chance you'll add support for IPFS in the backend?

In particular, this will enable running Dose behind [TorPlus](http://www.torplus.com). See also https://github.com/TimosCatell/TorPlusSite.

Thanks,
Timos

**Comment by GustavPS** [comment]
Sorry for (extremly) late reply. As of now we have no plans of adding support for IPFS. Mostly because I have never used it myself and see no need for running it behind TorPlus
